### ISSUE TITLE
/asplayer command

### ISSUE THREAD

**Issue by nomadjimbob** [STEMMechanics/Drustcraft#102]
Admins and Owner need a `/asplayer` command that removes their admin/owner group and sets them back as a standard player for testing purposes. This will help diagnose any issues that maybe non-replicate able as a admin/owner

**Comment by lstone01** [comment]
Could we also use the command to not be begged by other players and just be normal players?

**Comment by nomadjimbob** [comment]
Do we just remove the admin/owner tag completely? This command will still exist as it changes permissions but no matter what mode you are in, you are never displayed as a admin/owner
