### ISSUE TITLE
Harvesting

### ISSUE THREAD

**Issue by ProjectHSI** [STEMMechanics/Drustcraft#4]
Add the ability to right-click harvest crop blocks, Simular to older versions of Minecraft.

**Comment by nomadjimbob** [comment]
This should be converted to a buff and support a range with a new sickle tool. Higher level sickle tools should harvest and replant up to a 5x5 grid!

**Comment by nomadjimbob** [comment]
Converted to buff-harvesting

**Comment by nomadjimbob** [comment]
This is now completed ready for 1.3
