### ISSUE TITLE
Items sometimes don't stack when having a full inventory

### ISSUE THREAD

**Issue by ProjectHSI** [STEMMechanics/Drustcraft#6]
[See this video for more information](https://cdn.discordapp.com/attachments/887518510325067777/996593133611646996/2022-07-13_11-43-26.mp4)

Ore mining has been fixed, however certain things still don't work.

**Comment by ProjectHSI** [comment]
this bug has returned,

**Comment by ProjectHSI** [comment]
it's entirely possible i may have broken items

**Comment by ProjectHSI** [comment]
no /inventoryfix doesn't fix this issue

**Comment by nomadjimbob** [comment]
What are the items not stacking? How did you receive them?

**Comment by ProjectHSI** [comment]
sure...
- items in general
- drops from blocks
- that works,
- kinda hard, it corrects when i pick it up when i have 1 free inventory space, meaning the only way for you to investigate is to tp to one of these 'bugged' item entities.

**Comment by nomadjimbob** [comment]
Issue occurs when a player has no empty slots in their inventory. As the block drop does not yet contain the updated lore, there is no space in the players inventory to pick up the item, this the pick up item event does not fire to update the lore!

/inventoryfix does not fix this issue as it only fixes the inventory items (which are all correct) and that particular items is outside the inventory.

Item lore should be updated when it is spawned

**Comment by nomadjimbob** [comment]
Fixed in 1.3
